---
# connection
ansible_ssh_host: demo.madek.zhdk.ch
madek_external_hostname: demo.madek.zhdk.ch
ansible_ssh_port: 22
ansible_ssh_user: root

# storage
setup_storage_directories: true
madek_storage_dir: /srv/madekdata
madek_file_storage_dir: /srv/madekdata/attachments
madek_thumbnail_storage_dir: /srv/madekdata/attachments
madek_tmp_dir: /srv/madekdata/tmp

# audio and videos previews
zencoder_enabled: false
# NOTE: zencoder_api_key is included from secrets.yml
# zencoder_test_mode: True

# backups
# db_backups_enabled: False

# customizations
madek_webapp_html_extra_head_start: |
  <!--

  * * DEMO * DEMO * DEMO * DEMO * DEMO * DEMO * DEMO * *
       __       __                  __            __
  /  \     /  |                /  |          /  |
  $$  \   /$$ |  ______    ____$$ |  ______  $$ |   __
  $$$  \ /$$$ | /      \  /    $$ | /      \ $$ |  /  |
  $$$$  /$$$$ | $$$$$$  |/$$$$$$$ |/$$$$$$  |$$ |_/$$/
  $$ $$ $$/$$ | /    $$ |$$ |  $$ |$$    $$ |$$   $$<
  $$ |$$$/ $$ |/$$$$$$$ |$$ \__$$ |$$$$$$$$/ $$$$$$  \
  $$ | $/  $$ |$$    $$ |$$    $$ |$$       |$$ | $$  |
  $$/      $$/  $$$$$$$/  $$$$$$$/  $$$$$$$/ $$/   $$/

  * * DEMO * DEMO * DEMO * DEMO * DEMO * DEMO * DEMO * *

  -->

# madek_webapp_html_extra_head_end: |
#   <link rel="stylesheet" type="text/css" href="/local-theme.css">
